### ISSUE TITLE
[request] add option to not resume the process after frida was loaded.

### ISSUE THREAD

**Issue by nitanmarcel** [lico-n/ZygiskFrida#19]
I started using radare2 with r2frida, and I noticed that when normally r2frida would pause the process after spawning, while using ZygiskFrida the process continues making some early traces impossible

**Comment by lico-n** [comment]
I have taken a look about this but this is sadly not straightforward to do. 

ZygiskFrida injects frida using a gadget. The gadget by default resumes on attach without any way to configure it. It might be possible with a custom written gadget but I currently don't have enough knowledge about the frida codebasis to do so.

Maybe this is something that I can research in the future but for now that won't be possible. Any help on this would be very welcome.

If you want to trace something very early and regular frida-server is not possible, then you could try to run the Gadget in script mode. But that is pretty tedious because you can't do so interactively but as a last resort it might be enough.
