### ISSUE TITLE
I have a usage question to consult with

### ISSUE THREAD

**Issue by sy007** [lico-n/ZygiskFrida#22]
When I execute the `frida - U - N your. target. application - l xxx.js` command on the terminal, both the terminal and the app are blocked. How should I continue to run them?

<img width="724" alt="image" src="https://github.com/lico-n/ZygiskFrida/assets/19952631/bea746a0-c94d-4db6-8c6a-9b908eaec0fe">

I follow the help to execute resume

<img width="729" alt="image" src="https://github.com/lico-n/ZygiskFrida/assets/19952631/b24f22d3-ec2d-4caa-ae76-774e65162ac2">

**Comment by sy007** [comment]
This is my script file content `a.js`

```js
function main() {
	if (Java.available) {
		console.log("available");
		try {
			Java.performNow(function () {
				var activity = Java.use("android.app.Activity");
				var builderCls = Java.use("android.app.AlertDialog$Builder");
				var StringCls = Java.use("java.lang.String");
				activity.onCreate.overload("android.os.Bundle").implementation = function (savedInstanceState) {
					var builder = builderCls.$new(this);
					this.onCreate(savedInstanceState);
					builder.setTitle(StringCls.$new("hook tip"));
					builder.setMessage(StringCls.$new("hook!!"));
					builder.create().show();
				}
			});
			console.log("java over hook");
		} catch (e) {
			console.log("[!]Exception:" + +e.message);
		}

	}
}

setImmediate(main)
```

**Comment by lico-n** [comment]
This works fine for me. With this gadget there is no `resume` command because it automatically resumes after a frida client connects.

I tested your command `frida -U -n Gadget -l a.js` with your script on some random app that I have on my phone and it works.

Just some troubleshooting:
- does connecting without a script works for you or does the app also stay paused without?
- does it work on a different app?
- check `adb logcat -s ZygiskFrida` to see if it repeatedly detects the app after you have connected (this could be the app restarting due to some protections kicking in) 
- you can try to see if setting a start up delay works with this specific app set `start_up_delay_ms` to some bigger value like 10000 for 10seconds. Often app don't pause at all if injection time is late in the process and can also sometimes bypass early checks.

**Comment by sy007** [comment]
> This works fine for me. With this gadget there is no `resume` command because it automatically resumes after a frida client connects.
> 
> I tested your command `frida -U -n Gadget -l a.js` with your script on some random app that I have on my phone and it works.
> 
> Just some troubleshooting:
> 
> * does connecting without a script works for you or does the app also stay paused without?
> * does it work on a different app?
> * check `adb logcat -s ZygiskFrida` to see if it repeatedly detects the app after you have connected (this could be the app restarting due to some protections kicking in)
> * you can try to see if setting a start up delay works with this specific app set `start_up_delay_ms` to some bigger value like 10000 for 10seconds. Often app don't pause at all if injection time is late in the process and can also sometimes bypass early checks.

Great, thank you for your reply.
