### ISSUE TITLE
add support for kernelSU

### ISSUE THREAD

**Issue by IamLoot** [lico-n/ZygiskFrida#33]
Currently it is not working on kernelsu, so please add support for kernelSU!

**Comment by lico-n** [comment]
Hey, what is your setup? Are you using ZygiskNext with kernelSU? Are you able to run any other Zygisk based modules?

**Comment by IamLoot** [comment]
> Hey, what is your setup? Are you using ZygiskNext with kernelSU? Are you able to run any other Zygisk based modules?

Yes, I'm using zygiskNext on kernelsu and yeh I'm able to use other zygiskNext based module and those are working fine. Only problem on your this module. Btw the problem is it is only transferring config.json.example file on /data/local/tmp/re.zyg.fri/ directory when i flash and reboot the device. While it is working when I'm on magisk

**Comment by lico-n** [comment]
I have a guess based that only the config.json.example is in the directory. 

The module is using the busybox of magisk to extract the gadgets. So I assume it can't find the busybox binary because it is on a different path.

Could you maybe download and try out the version here? I have no kernelsu device at hand currently to quickly test it.

https://github.com/lico-n/ZygiskFrida/actions/runs/8857846035

**Comment by IamLoot** [comment]
> I have a guess based that only the config.json.example is in the directory.
> 
> The module is using the busybox of magisk to extract the gadgets. So I assume it can't find the busybox binary because it is on a different path.
> 
> Could you maybe download and try out the version here? I have no kernelsu device at hand currently to quickly test it.
> 
> https://github.com/lico-n/ZygiskFrida/actions/runs/8857846035

Yes, this worked. Thank you!
